// Recovered exact GLSL from production bundle. Original names: CO, wO, wE, TE.

export const paddleVertexShader = "\n  varying vec2 vUv;\n  varying vec3 vN;\n  varying vec3 vView;\n  void main() {\n    vUv = uv;\n    vec4 mv = modelViewMatrix * vec4(position, 1.0);\n    vView = -mv.xyz;\n    vN = normalMatrix * normal;\n    gl_Position = projectionMatrix * mv;\n  }\n";

export const paddleFragmentShader = "\n  varying vec2 vUv;\n  varying vec3 vN;\n  varying vec3 vView;\n\n  uniform vec3 uCore;\n  uniform vec3 uEdge;\n  uniform vec3 uAccent;\n  uniform float uCharge;\n  uniform float uHit;\n  uniform float uEnergy;\n\n  void main() {\n    vec2 p = (vUv - 0.5) * 2.0;\n    float r = length(p);\n\n    vec3 col = mix(uCore, uEdge, smoothstep(0.08, 1.05, r));\n    float topLight = smoothstep(-0.75, 0.85, p.y);\n    col *= 0.92 + topLight * 0.1;\n    col *= 1.0 - 0.12 * smoothstep(0.62, 1.0, r);\n\n    float spec = smoothstep(0.42, 0.0, length(p - vec2(0.26, 0.34)));\n    col += vec3(1.0) * spec * 0.035;\n\n    float fres = pow(1.0 - clamp(dot(normalize(vN), normalize(vView)), 0.0, 1.0), 2.4);\n    col += uEdge * fres * 0.08;\n\n    float cr = smoothstep(0.08, 0.0, abs(r - uCharge)) * uCharge;\n    col += uAccent * cr * 0.55;\n    col *= 1.0 + uEnergy * 0.16;\n    col = mix(col, mix(uAccent, vec3(1.0), 0.55), clamp(uHit, 0.0, 1.0) * 0.55);\n\n    gl_FragColor = vec4(col, 1.0);\n  }\n";

export const skyVertexShader = "\n  varying vec2 vUv;\n  void main() {\n    vUv = uv;\n    gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);\n  }\n";

export const skyFragmentShader = "\n  precision highp float;\n  varying vec2 vUv;\n\n  uniform float uTime;\n  uniform vec3  uZenith;   // calm bone wall\n  uniform vec3  uEdge;     // luminous warm cream — light pool + number tint\n  uniform float uHorizon;  // uv.y the light pool centres on\n  uniform float uHeat;\n  uniform float uHit;\n  uniform float uBounce;\n  uniform float uSmash;\n  uniform float uPoint;    // generic point-scored flash (arena.score)\n  uniform float uWin;        // +1 = you won the match, -1 = you lost, 0 = live\n  uniform float uWinFlash;   // decaying bloom on the win/loss beat\n\n  float hash(vec2 p) { return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453123); }\n\n  void main() {\n    vec2 uv = vUv;\n\n    // --- soft warm wall: a calm bone field with light POOLING around the numbers,\n    //     swelling on heat + contact (the numbers read as soft light on the wall).\n    vec3 col = uZenith;\n    float wallShade = smoothstep(0.0, 1.0, uv.y);\n    col *= mix(0.88, 1.04, wallShade);\n    float cornerShade = smoothstep(0.72, 1.0, abs(uv.x - 0.5) * 2.0);\n    col *= 1.0 - cornerShade * 0.08;\n    col *= 1.0 - smoothstep(0.22, 0.0, uv.y) * 0.08;\n    float cd = distance(uv, vec2(0.5, uHorizon + 0.03));\n    float pool = exp(-cd * cd * 3.0);\n    float poolPunch = uHit * 0.06 + uBounce * 0.03 + uSmash * 0.16 + uPoint * 0.08;\n    col = mix(col, uEdge, pool * 0.45);\n    col += uEdge * pool * (0.05 + uHeat * 0.05 + poolPunch);\n\n    // Anti-banding belongs to the smooth clay wall, not the luminous scoreboard body.\n    col += (hash(gl_FragCoord.xy) - 0.5) / 420.0;\n\n    // --- match win / loss wash over the whole wall\n    float winP = max(0.0, uWin);\n    float winA = max(0.0, -uWin);\n    col *= 1.0 + winP * (0.28 + uWinFlash * 0.8);\n    col += uEdge * winP * (0.1 + uWinFlash * 0.4) * pool;\n    float ll = dot(col, vec3(0.299, 0.587, 0.114));\n    col = mix(col, vec3(ll) * vec3(0.95, 0.92, 0.9), winA * 0.45); // loss: desaturate\n    col *= 1.0 - winA * 0.24;                                       // loss: dim\n\n    // heat warms the wall a touch\n    col = mix(col, col * vec3(1.05, 1.01, 0.96), uHeat * 0.4);\n\n    gl_FragColor = vec4(col, 1.0);\n  }\n";
